include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true

    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true

    depend_on_referenced_packages: true
    avoid_relative_lib_imports: true

    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
